In [2]:
from regelum.system import System
from regelum.simulator import SciPy
from regelum.simulator import CasADi
from regelum.scenario import Scenario
from regelum.policy import Policy
from regelum import callback

from src.system import HydraulicSystemFull

from src.policy import PDController

import matplotlib.pyplot as plt
import numpy as np

# Define the initial state (initial position of the kinematic point).
initial_state = np.array([1e3, 0, 0])  # Start at position (2, 2)

# Initialize the kinematic point system.
h_system = HydraulicSystemFull() # HydraulicSystem()

# Instantiate a simulator for the kinematic point system.
simulator =  SciPy(
    system=h_system, state_init=initial_state, time_final=10e-3, max_step=1e-3
)

scenario = Scenario(
    policy=PDController(
        system=h_system,
        sampling_time=1e-3
    ),
    simulator=simulator,
    sampling_time=1e-3,
    N_episodes=5,
    N_iterations=5,
)

scenario.run()

[1000.    0.    0.]
[0.]
Here: [[0.20568506]]
observation:  [[-0.05448337 -0.00769512]]
[1.00000000e+03 3.73361949e+00 1.58301312e-05]
[[0.20568506]]
[1.00000000e+03 5.54863104e+00 3.32478114e-05]
[[0.20568506]]
[1.00000000e+03 6.94033157e+00 5.83231744e-05]
[[0.20568506]]
[1.00000000e+03 7.36762531e+00 8.33985374e-05]
[[0.20568506]]
[1.00000000e+03 7.47255420e+00 1.10894177e-04]
[[0.20568506]]
[1.00000000e+03 7.49521982e+00 1.46509175e-04]
[[0.20568506]]
[1.00000000e+03 7.49816554e+00 1.93675031e-04]
[[0.20568506]]
[1.00000000e+03 7.49565448e+00 2.58155784e-04]
[[0.20568506]]
[1.00000000e+03 7.49319166e+00 3.18347857e-04]
[[0.20568506]]
[1.00000000e+03 7.48918117e+00 3.78539931e-04]
[[0.20568506]]
[1.00000000e+03 7.48709325e+00 4.35921417e-04]
[[0.20568506]]
[1.00000000e+03 7.49097410e+00 4.88515664e-04]
[[0.20568506]]
[1.00000000e+03 7.49440018e+00 5.40108812e-04]
[[0.20568506]]
[1.00000000e+03 7.49451259e+00 5.95882950e-04]
[[0.20568506]]
[1.0000000e+03 7.4909031e+00 6.5655691e-04]


KeyboardInterrupt: 

In [1]:
from regelum.system import System
from regelum.simulator import SciPy
from regelum.simulator import CasADi
from regelum.scenario import Scenario
from regelum.policy import Policy
from regelum import callback

import matplotlib.pyplot as plt
import numpy as np

class KinematicPoint(System):
    _name = "kinematic-point"
    _system_type = "diff_eqn"
    _dim_state = 2
    _dim_inputs = 2
    _dim_observation = 2
    _observation_naming = _state_naming = ["x", "y"]
    _inputs_naming = ["v_x", "v_y"]
    _action_bounds = [[-10.0, 10.0], [-10.0, 10.0]]

    # receive_action

    def _compute_state_dynamics(self, time, state):
        return self.inputs  # The velocity inputs directly define the rate of change of position.
    
    def compute_closed_loop_rhs(self, time, state):
        return self.inputs  # The velocity inputs directly define the rate of change of position.
    
class PDController(Policy):
    def __init__(
        self,
        system: KinematicPoint,
        sampling_time: float,
    ):
        super().__init__()
        self.system = system
        self.sampling_time = sampling_time
        
        self.pd_coefs: list[float] = [
            1,
            0.1,
        ]
        
    def get_action(self, observation):

        return np.array([[-observation[0, 0], -observation[0, 1]]])

# Define the initial state (initial position of the kinematic point).
initial_state = np.array([2.0, 2.0])  # Start at position (2, 2)

# Initialize the kinematic point system.
kinematic_point = KinematicPoint()

# Instantiate a simulator for the kinematic point system.
simulator =  SciPy(
    system=kinematic_point, state_init=initial_state, time_final=4, max_step=0.1
)

scenario = Scenario(
    policy=PDController(
        system=kinematic_point,
        sampling_time=0.01
    ),
    simulator=simulator,
    sampling_time=0.01,
    N_episodes=5,
    N_iterations=5,
)

scenario.run()

should be
StateJ:  [2. 2.] [0. 0.]
[2. 2.]
[0. 0.]
Here: [[-2. -2.]]
observation:  [[2. 2.]]
StateJ:  [1.99999818 1.99999818] [[-2. -2.]]
[1.99999818 1.99999818]
[[-2. -2.]]
StateJ:  [1.99997818 1.99997818] [[-2. -2.]]
[1.99997818 1.99997818]
[[-2. -2.]]
StateJ:  [1.99977818 1.99977818] [[-2. -2.]]
[1.99977818 1.99977818]
[[-2. -2.]]
StateJ:  [1.99777818 1.99777818] [[-2. -2.]]
[1.99777818 1.99777818]
[[-2. -2.]]
StateJ:  [1.97777818 1.97777818] [[-2. -2.]]
[1.97777818 1.97777818]
[[-2. -2.]]
Here: [[-1.97777818 -1.97777818]]
observation:  [[1.97777818 1.97777818]]
StateJ:  [1.77979782 1.77979782] [[-1.97777818 -1.97777818]]
[1.77979782 1.77979782]
[[-1.97777818 -1.97777818]]
Here: [[-1.77979782 -1.77979782]]
observation:  [[1.77979782 1.77979782]]
StateJ:  [1.60001353 1.60001353] [[-1.77979782 -1.77979782]]
[1.60001353 1.60001353]
[[-1.77979782 -1.77979782]]
Here: [[-1.60001353 -1.60001353]]
observation:  [[1.60001353 1.60001353]]
StateJ:  [1.43837352 1.43837352] [[-1.60001353 -1.6000

In [3]:
from regelum.system import System
from regelum.simulator import SciPy
from regelum.simulator import CasADi

import matplotlib.pyplot as plt
import numpy as np


class KinematicPoint(System):
    _name = "kinematic-point"
    _system_type = "diff_eqn"
    _dim_state = 2
    _dim_inputs = 2
    _dim_observation = 2
    _observation_naming = _state_naming = ["x", "y"]
    _inputs_naming = ["v_x", "v_y"]
    _action_bounds = [[-10.0, 10.0], [-10.0, 10.0]]

    def _compute_state_dynamics(self, time, inputs):
        return inputs  # The velocity inputs directly define the rate of change of position.

def get_action(state):
    return (
        -state
    )  # Stabilizing action: control input is the negative of the system state.

# Define the initial state (initial position of the kinematic point).
initial_state = np.array([2.0, 2.0])  # Start at position (2, 2)

# Initialize the kinematic point system.
kinematic_point = KinematicPoint()

# Instantiate a simulator for the kinematic point system.
simulator =  SciPy(
    system=kinematic_point, state_init=initial_state, time_final=4, max_step=0.1
)

state_history = [initial_state.flatten()]  # Store the initial state.
times = [0.0]

for _ in range(int(simulator.time_final / simulator.max_step)):
    action = get_action(
        simulator.state
    )  # Compute the action based on the current state.
    simulator.receive_action(action)  # Provide the action to the simulator.
    simulator.do_sim_step()  # Perform one simulation step.
    state_history.append(simulator.state.flatten())  # Store the state after the step.
    times.append(simulator.time)

state_history = np.array(state_history)  # Convert history to numpy array for plotting.
times = np.array(times)  # Convert history to numpy array for plotting.

print(state_history)

fig, (ax_x, ax_y, ax_theta) = plt.subplots(1, 3, figsize=(12, 4))

ax_x.plot(times, state_history[:, 0], marker="o", markersize=4)
ax_x.set_title("X Position [m]")
ax_x.set_xlabel("Time [s]")
ax_x.grid(True)

ax_y.plot(times, state_history[:, 1], marker="o", markersize=4)
ax_y.set_title("Y Position [m]")
ax_y.set_xlabel("Time [s]")
ax_y.grid(True)

fig.savefig("run_results.png")
plt.show()

[[ 2.          2.        ]
 [ 2.000002    2.000002  ]
 [ 2.000022    2.000022  ]
 [ 2.00022201  2.00022201]
 [ 2.00222323  2.00222323]
 [ 2.02234591  2.02234591]
 [ 2.23503789  2.23503789]
 [ 2.47009888  2.47009888]
 [ 2.72988144  2.72988144]
 [ 3.01698558  3.01698558]
 [ 3.33428473  3.33428473]
 [ 3.68495451  3.68495451]
 [ 4.07250456  4.07250456]
 [ 4.50081361  4.50081361]
 [ 4.97416831  4.97416831]
 [ 5.49730616  5.49730616]
 [ 6.0754629   6.0754629 ]
 [ 6.71442491  6.71442491]
 [ 7.42058714  7.42058714]
 [ 8.20101711  8.20101711]
 [ 9.06352561  9.06352561]
 [10.01674492 10.01674492]
 [11.07021518 11.07021518]
 [12.23447988 12.23447988]
 [13.52119136 13.52119136]
 [14.94322747 14.94322747]
 [16.51482043 16.51482043]
 [18.25169926 18.25169926]
 [20.17124723 20.17124723]
 [22.29267582 22.29267582]
 [24.63721701 24.63721701]
 [27.22833575 27.22833575]
 [30.09196483 30.09196483]
 [33.2567644  33.2567644 ]
 [36.75440886 36.75440886]
 [40.61990379 40.61990379]
 [44.89193637 44.89193637]
 

/tmp/ipykernel_426399/2237497027.py:68: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()


In [3]:
import pytest
import numpy as np

from regelum.scenario import Scenario
from regelum.simulator import SciPy
from regelum.simulator import CasADi

from src.system import HydraulicSystem
from src.policy import PDController

from regelum import callback

sampling_time = 1e-3

system = HydraulicSystem # HydraulicSystem()

simulator = CasADi( #SciPy(
    system=system,
    state_init = np.array([1e3, 0]),
    time_final = 10e-3,
)

scenario = Scenario(
    policy=PDController(
        system=system,
        sampling_time=sampling_time
    ),
    simulator=simulator,
    sampling_time=0.01,
    N_episodes=1,
    N_iterations=1,
)

scenario.run()

ImportError: cannot import name 'HydraulicSystem' from 'src.system' (/home/kalexu/Projects/AdvContrMethods/Project/src/system.py)

In [1]:
import numpy as np
from src.system import HydraulicSystem
from src.policy import PDController

from regelum.scenario import Scenario
from regelum.simulator import SciPy

# from regelum.system import System
from regelum.utils import rg


system = HydraulicSystem()

simulator = SciPy(
    system=system,
    state_init = np.array([1e3, 0, 0, 0]),
    time_final = 10e-3,
)

AttributeError: 'HydraulicSystem' object has no attribute 'compute_closed_loop_rhs'

In [2]:
system.compute_state_dynamics(0, np.array([2.0, 0, 0]), inputs=np.array([[10]]))

array([[    0.,     0., 10000.]])