This notebook is used to test the system simulator.

# Import libraries

In [1]:

from regelum.scenario import Scenario
import numpy as np
from tqdm.notebook import tqdm

import sys
sys.path.append('../')

from src.system import HydraulicSystemFull
from src.policy import PDController
from src.simulator import SciPy

# Run simulation

In [2]:
# sampling_time = 1e-3

# # Define the initial state (initial position of the kinematic point).
# initial_state = np.array([1e3, 0, 0])

# # Initialize the kinematic point system.
# h_system = HydraulicSystemFull()

# # Instantiate a simulator for the hydraulic system
# simulator = SciPy(
#     system=h_system, 
#     state_init=initial_state, 
#     time_final=10e-3, 
#     max_step=sampling_time
# )

# scenario = Scenario(
#     policy=PDController(
#         system=h_system,
#         sampling_time=sampling_time,
#     ),
#     simulator=simulator,
#     sampling_time=sampling_time,
#     N_episodes=1,
#     N_iterations=1,
# )

# scenario.run()

Instantiating Simulator and Policy

In [3]:
sampling_time = 1e-3
final_time = 10e-3

# Define the initial state (initial position of the kinematic point).
initial_state = np.array([1e3, 0, 0])

# Initialize the kinematic point system.
h_system = HydraulicSystemFull()

# Instantiate a simulator for the hydraulic system
simulator = SciPy(
    system=h_system, 
    state_init=initial_state, 
    time_final=final_time, 
    max_step=sampling_time
)

pd_policy = PDController(
    system=h_system,
    sampling_time=sampling_time,
)

Running the Simulation loop

Calculation with RG takes 18+ minutes to finish stage 4.
Now np. is used instead.

In [4]:
state_history = [initial_state.flatten()]  # Store the initial state.
observation_history = [simulator.observation_init.flatten()]
times = [0.0]

for _ in tqdm(range(int(simulator.time_final / simulator.max_step))):
    action = pd_policy.get_action(
        simulator.observation
    )  # Compute the action based on the current state.
    simulator.receive_action(action)  # Provide the action to the simulator.
    simulator.do_sim_step()  # Perform one simulation step.
    state_history.append(simulator.state.flatten())  # Store the state after the step.
    observation_history.append(simulator.observation.flatten()) # Store the observation after the step.
    times.append(simulator.time)

state_history = np.array(state_history)  # Convert history to numpy array for plotting.
observation_history = np.array(observation_history) # Convert history to numpy array for plotting.
times = np.array(times)  # Convert history to numpy array for plotting.

  0%|          | 0/10 [00:00<?, ?it/s]

KeyboardInterrupt: 

In [5]:
state_history = np.array(state_history)  # Convert history to numpy array for plotting.
observation_history = np.array(observation_history) # Convert history to numpy array for plotting.
times = np.array(times)  # Convert history to numpy array for plotting.

In [6]:
display('times')
display(times)
display(f'Time shape = {times.shape}')
display('state_history')
display(state_history)
display(f'State history shape = {state_history.shape}')
display('observation_history')
display(observation_history)
display(f'Observation history shape = {observation_history.shape}')

'times'

array([0.   , 0.001, 0.002, 0.003, 0.004])

'Time shape = (5,)'

'state_history'

array([[1.00000000e+03, 0.00000000e+00, 0.00000000e+00],
       [1.00007489e+03, 1.49268031e+02, 1.00000000e+01],
       [1.00029837e+03, 2.96864950e+02, 2.00000000e+01],
       [1.00052227e+03, 1.60534649e+02, 1.07520948e+01],
       [1.00060821e+03, 1.12578390e+01, 7.52094835e-01]])

'State history shape = (5, 3)'

'observation_history'

array([[ 2.80125973e-02, -2.40545833e-03],
       [ 2.26780220e-01,  5.48289199e+02],
       [ 1.09236943e+00,  1.09040812e+03],
       [ 2.00358810e+00,  5.89659372e+02],
       [ 2.20362609e+00,  4.13443151e+01]])

'Observation history shape = (5, 2)'

In [2]:
from src.system import HydraulicSystemSimpleRg

sampling_time = 1e-3
final_time = 10e-3

# Define the initial state (initial position of the kinematic point).
initial_state = np.array([1e3, 0, 0])

# Initialize the kinematic point system.
h_system = HydraulicSystemSimpleRg()

# Instantiate a simulator for the hydraulic system
simulator = SciPy(
    system=h_system, 
    state_init=initial_state, 
    time_final=final_time, 
    max_step=sampling_time
)

pd_policy = PDController(
    system=h_system,
    sampling_time=sampling_time,
)

In [3]:
state_history = [initial_state.flatten()]  # Store the initial state.
observation_history = [simulator.observation_init.flatten()]
times = [0.0]

for _ in tqdm(range(int(simulator.time_final / simulator.max_step))):
    action = pd_policy.get_action(
        simulator.observation
    )  # Compute the action based on the current state.
    simulator.receive_action(action)  # Provide the action to the simulator.
    simulator.do_sim_step()  # Perform one simulation step.
    state_history.append(simulator.state.flatten())  # Store the state after the step.
    observation_history.append(simulator.observation.flatten()) # Store the observation after the step.
    times.append(simulator.time)

state_history = np.array(state_history)  # Convert history to numpy array for plotting.
observation_history = np.array(observation_history) # Convert history to numpy array for plotting.
times = np.array(times)  # Convert history to numpy array for plotting.

  0%|          | 0/10 [00:00<?, ?it/s]

KeyboardInterrupt: 

In [4]:
state_history = np.array(state_history)  # Convert history to numpy array for plotting.
observation_history = np.array(observation_history) # Convert history to numpy array for plotting.
times = np.array(times)  # Convert history to numpy array for plotting.

In [5]:
display('times')
display(times)
display(f'Time shape = {times.shape}')
display('state_history')
display(state_history)
display(f'State history shape = {state_history.shape}')
display('observation_history')
display(observation_history)
display(f'Observation history shape = {observation_history.shape}')

'times'

array([0.   , 0.001, 0.002, 0.003, 0.004])

'Time shape = (5,)'

'state_history'

array([[1.00000000e+03, 0.00000000e+00, 0.00000000e+00],
       [1.00007513e+03, 1.49746556e+02, 1.00000000e+01],
       [1.00029931e+03, 2.98187868e+02, 2.00000000e+01],
       [1.00052382e+03, 1.59681955e+02, 1.06602741e+01],
       [1.00060866e+03, 9.90626045e+00, 6.60274078e-01]])

'State history shape = (5, 3)'

'observation_history'

array([[0.00000000e+00, 0.00000000e+00],
       [2.75961074e-01, 5.50033263e+02],
       [1.09940921e+00, 1.09527224e+03],
       [1.92405424e+00, 5.86526925e+02],
       [2.23566766e+00, 3.63866316e+01]])

'Observation history shape = (5, 2)'