This notebook is used to test the system simulator.

# Import libraries

In [ ]:

from regelum.scenario import Scenario
import numpy as np
from tqdm.notebook import tqdm

import sys
sys.path.append('../')

from src._system import HydraulicSystemFull
from src._system import HydraulicSystemSimpleClose
from src.policy import PDController
from src.simulator import SciPy

# Test influence of the "x_th_eps" to the full system

Calculation with RG takes more time to calculate vs numpy.

Test that larger x_th_eps reduces calculation time.

Instantiating Simulator and Policy

In [2]:
sampling_time = 1e-3
final_time = 10e-3

# Define the initial state (initial position of the kinematic point).
initial_state = np.array([1e3, 0, 0])

# Initialize the kinematic point system.
h_system = HydraulicSystemFull()

# Instantiate a simulator for the hydraulic system
simulator = SciPy(
    system=h_system, 
    state_init=initial_state, 
    time_final=final_time, 
    max_step=sampling_time
)

pd_policy = PDController(
    system=h_system,
    sampling_time=sampling_time,
)

Running the Simulation loop

In [3]:
state_history = [initial_state.flatten()]  # Store the initial state.
observation_history = [simulator.observation_init.flatten()]
times = [0.0]

for _ in tqdm(range(int(simulator.time_final / simulator.max_step))):
    action = pd_policy.get_action(
        simulator.observation
    )  # Compute the action based on the current state.
    simulator.receive_action(action)  # Provide the action to the simulator.
    simulator.do_sim_step()  # Perform one simulation step.
    state_history.append(simulator.state.flatten())  # Store the state after the step.
    observation_history.append(simulator.observation.flatten()) # Store the observation after the step.
    times.append(simulator.time)

state_history = np.array(state_history)  # Convert history to numpy array for plotting.
observation_history = np.array(observation_history) # Convert history to numpy array for plotting.
times = np.array(times)  # Convert history to numpy array for plotting.

  0%|          | 0/10 [00:00<?, ?it/s]

KeyboardInterrupt: 

In [4]:
state_history = np.array(state_history)  # Convert history to numpy array for plotting.
observation_history = np.array(observation_history) # Convert history to numpy array for plotting.
times = np.array(times)  # Convert history to numpy array for plotting.

display('times')
display(times)
display(f'Time shape = {times.shape}')
display('state_history')
display(state_history)
display(f'State history shape = {state_history.shape}')
display('observation_history')
display(observation_history)
display(f'Observation history shape = {observation_history.shape}')

'times'

array([0.   , 0.001, 0.002, 0.003, 0.004])

'Time shape = (5,)'

'state_history'

array([[1000.        ,    0.        ,    0.        ],
       [1000.07545501,  149.06904662,   10.        ],
       [1000.29893225,  297.27710393,   20.        ],
       [1000.52551594,  179.87710697,   12.04416768],
       [1000.63073501,   30.5724017 ,    2.04416768]])

'State history shape = (5, 3)'

'observation_history'

array([[ 2.21740170e-02, -1.01718372e-02],
       [ 3.02985018e-01,  5.47553392e+02],
       [ 9.93307787e-01,  1.09192935e+03],
       [ 2.01869604e+00,  6.60716385e+02],
       [ 2.30573327e+00,  1.12285754e+02]])

'Observation history shape = (5, 2)'

## Simple system

In [2]:
sampling_time = 1e-3
final_time = 10e-3

# Define the initial state (initial position of the kinematic point).
initial_state = np.array([1e3, 0, 0])

# Initialize the kinematic point system.
h_system = HydraulicSystemSimpleClose()

# Instantiate a simulator for the hydraulic system
simulator = SciPy(
    system=h_system, 
    state_init=initial_state, 
    time_final=final_time, 
    max_step=sampling_time
)

pd_policy = PDController(
    system=h_system,
    sampling_time=sampling_time,
)

In [3]:
state_history = [initial_state.flatten()]  # Store the initial state.
observation_history = [simulator.observation_init.flatten()]
times = [0.0]

for _ in tqdm(range(int(simulator.time_final / simulator.max_step))):
    action = pd_policy.get_action(
        simulator.observation
    )  # Compute the action based on the current state.
    simulator.receive_action(action)  # Provide the action to the simulator.
    simulator.do_sim_step()  # Perform one simulation step.
    state_history.append(simulator.state.flatten())  # Store the state after the step.
    observation_history.append(simulator.observation.flatten()) # Store the observation after the step.
    times.append(simulator.time)

state_history = np.array(state_history)  # Convert history to numpy array for plotting.
observation_history = np.array(observation_history) # Convert history to numpy array for plotting.
times = np.array(times)  # Convert history to numpy array for plotting.

  0%|          | 0/10 [00:00<?, ?it/s]

KeyboardInterrupt: 

In [4]:
state_history = np.array(state_history)  # Convert history to numpy array for plotting.
observation_history = np.array(observation_history) # Convert history to numpy array for plotting.
times = np.array(times)  # Convert history to numpy array for plotting.

display('times')
display(times)
display(f'Time shape = {times.shape}')
display('state_history')
display(state_history)
display(f'State history shape = {state_history.shape}')
display('observation_history')
display(observation_history)
display(f'Observation history shape = {observation_history.shape}')

'times'

array([0.   , 0.001, 0.002, 0.003, 0.004])

'Time shape = (5,)'

'state_history'

array([[1.00000000e+03, 0.00000000e+00, 0.00000000e+00],
       [1.00007546e+03, 1.49069047e+02, 1.00000000e+01],
       [1.00029893e+03, 2.97277104e+02, 2.00000000e+01],
       [1.00052300e+03, 1.62556486e+02, 1.08871308e+01],
       [1.00061096e+03, 1.49623659e+01, 8.87130773e-01]])

'State history shape = (5, 3)'

'observation_history'

array([[-4.01643304e-02, -1.20029677e-02],
       [ 2.51551830e-01,  5.47542985e+02],
       [ 1.08201639e+00,  1.09192451e+03],
       [ 1.97648474e+00,  5.97094446e+02],
       [ 2.32805304e+00,  5.49504565e+01]])

'Observation history shape = (5, 2)'